osx_image: xcode7.3

language:
  - ruby

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

env:
  global:
  - NODE_VERSION=5

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.npm

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - clang-3.7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - gem install --no-rdoc --no-ri fpm

install:
- nvm install $NODE_VERSION
- npm install npm -g
- npm prune
- npm install

script:
- npm test
- npm run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
