platform:
  - x64

cache:
  - node_modules
  - 'app\node_modules'
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: nhMGmGZ2dNrFGEPqE/eDWfHEe0XNMiRDcULDamPndid8JOgbBVZYuMU6l+o5yKlE
  CSC_LINK:
    secure: Lg1zhuSQkaU/3rt6uwRnPIwOTVsoFeFiZHWw0hrG/NmwNMOgWEsBFWPa6zsXxF3DTZydBgBJkX4IjRcQVJYgUgUpcZgsOv/epsVa48HI9G0=
  CSC_KEY_PASSWORD:
    secure: dA6IrWnlJ4VxqELpX+CWz//4n840oG/4JLCqZH67z2XI5IeVWbyL2NuGPs0ULSfo

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm test
  - npm run dist

test: off
