platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: +qlfoqzL101lT4HceVcCuDAHcjAKGHBEExEFpjR7u+Rkl8CK9gD8riudhuXqjnmy

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm update

build_script:
  - node --version
  - npm --version
  - npm test
  - npm run dist

artifacts:
  - path: dist\win-x64\*.exe
  - path: dist\win-x64\*.nupkg

test: off
