platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm update

build_script:
  - node --version
  - npm --version
  - npm test
  - npm run dist

artifacts:
  - path: dist\win-x64\*.exe
  - path: dist\win-x64\*.nupkg

deploy:
  description: 'NodeCG Dashboard'
  provider: GitHub
  auth_token:
    secure: QsNzNI+W/pNpsNENqw8K48RZktiuNUmXu7encr+wIg1SbHte4y0tB4Zr38zif1hf
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only

test: off
